export const LANG = {
    ru: {
        app_name: "SmartNotes",
        slogan: "Ваши мысли. В порядке.",
        login: "Вход в систему",
        login_google: "Войти через Google",
        all_notes: "Все записи",
        favorites: "Важное",
        archive: "Архив",
        hidden_notes: "Спрятанное",
        future_notes: "На будущее",
        folders: "ПАПКИ",
        folders_overview: "Папки",
        about: "О нас",
        rate: "Оценить",
        settings: "Настройки",
        switch_acc: "Сменить",
        logout: "Выйти",
        empty: "Здесь пока пусто",
        general: "Общие",
        language: "Язык",
        appearance: "Внешний вид",
        presets: "Пресеты",
        manual: "Ручная настройка",
        c_text: "Текст",
        c_accent: "Акцент",
        c_bg: "Фон",
        reset: "Сбросить",
        close: "Закрыть",
        save: "Сохранить",
        team: "Команда",
        contact_us: "Связаться с нами:",
        send: "Отправить",
        cancel: "Отмена",
        yes: "Да",
        search: "Поиск...",
        note_title: "Заголовок",
        note_tags: "#тег (Enter)",
        feedback_placeholder: "Поделитесь впечатлениями...",
        note_actions: "Действия",
        audio_note: "Аудио",
        download_note: "Скачать файл",
        upload_note: "Отправить в облако",
        photo_editor: "Редактор фото",
        folders_settings: "Папки",
        folder_view_mode: "Отображение папок в меню",
        folder_view_compact: "В боковой панели",
        folder_view_full: "Полный экран",
        reduce_motion: "Уменьшить анимации",
        visual_effects: "Визуальные эффекты",
        editor_settings: "Настройки редактора",
        view_notes: "Все записи",
        view_favorites: "Важное",
        view_archive: "Архив",
        view_hidden: "Спрятанное",
        view_future: "На будущее",
        view_folder: "Папка",
        view_folders: "Папки",
        view_locked: "Защита заметок",
        hidden_empty: "Нет скрытых заметок",
        future_empty: "Нет заметок на будущее",
        note_single: "заметка",
        note_plural: "заметок",
        folders_empty: "Нет папок",
        pin_note: "Закрепить",
        unpin_note: "Открепить",
        favorite_note: "Важное",
        archive_note: "Архивировать",
        restore_note: "Вернуть",
        untitled_note: "Без названия",
        empty_note: "Нет содержимого",
        locked_note: "Защищено",
        new_folder: "Новая папка",
        folder_placeholder: "Название...",
        folder_empty: "Введите название папки",
        folder_exists: "Папка уже существует",
        folder_limit: "Лимит папок достигнут",
        rename_folder: "Переименовать папку",
        archived: "В архиве",
        restored: "Восстановлено",
        saving: "Сохранение...",
        saved: "Сохранено",
        rate_required: "Поставьте оценку",
        feedback_thanks: "Спасибо!",
        order_updated: "Порядок обновлен",
        undo: "Отменить",
        import_file: "Импортировать файл",
        import_invalid: "Неверный формат файла",
        import_empty: "Файлы не содержат заметок",
        import_success: "Импортировано",
        import_failed: "Ошибка импорта",
        download_success: "Файл сохранен",
        drive_connected: "Google Drive подключен",
        drive_unavailable: "Сервис Drive недоступен",
        drive_saved: "Загружено в Drive",
        drive_error: "Ошибка синхронизации",
        share_invalid: "Ссылка недействительна",
        share_missing: "Заметка не найдена",
        share_title: "Ссылка",
        mic_unsupported: "Микрофон не поддерживается",
        mic_denied: "Нет доступа к микрофону",
        recording: "Запись...",
        reminder_set: "Напоминание",
        confirm_delete: "Удалить?",
        confirm_exit: "Выйти?",
        confirm_account: "Сменить аккаунт?",
        confirm_delete_folder: "Удалить папку?",
        confirm_default: "Подтвердите",
        auth_unavailable: "Авторизация недоступна",
        move_toolbar: "Переместить панель",
        toolbar_show: "Показать панель инструментов",
        toolbar_hide: "Скрыть панель инструментов",
        tool_bold: "Жирный",
        tool_italic: "Курсив",
        tool_underline: "Подчеркнуть",
        tool_bullets: "Маркированный список",
        tool_numbered: "Нумерованный список",
        tool_image: "Изображение",
        tool_sketch: "Рисунок",
        tool_align: "Выравнивание",
        tool_clear: "Очистить формат",
        hide_note: "Убрать с глаз долой",
        unhide_note: "Вернуть",
        note_hidden: "Заметка скрыта",
        note_unhidden: "Заметка возвращена",
        future_note: "На будущее",
        future_clear: "Снять напоминание",
        future_saved: "Заметка отложена",
        future_cleared: "Отложенное снято",
        future_required: "Выберите дату",
        copy_text: "Копировать текст",
        copy_success: "Скопировано",
        copy_failed: "Не удалось скопировать",
        share_imported: "Заметка добавлена",
        polls: "Опросы",
        poll_title: "Опрос",
        poll_topic_label: "Тема опроса",
        poll_answer_label: "Ответ",
        poll_required: "Заполните опрос",
        poll_failed: "Не удалось отправить опрос",
        poll_thanks: "Спасибо за ответ",
        sketch_inline_title: "Рисование",
        sketch_inline_aria: "Рисование в редакторе",
        system_override: "System Override",
        close_menu: "Закрыть меню",
        add_folder: "Создать папку",
        open_menu: "Открыть меню",
        search_aria: "Поиск заметок",
        create_note: "Создать заметку",
        create_folder: "Создать папку",
        editor: "Редактор",
        back: "Назад",
        redo: "Повторить",
        delete_note: "Удалить заметку",
        note_title_aria: "Заголовок заметки",
        note_body_aria: "Текст заметки",
        note_tags_aria: "Добавить тег",
        save_note: "Сохранить",
        editor_pages: "Страницы",
        page_prev: "Предыдущая страница",
        page_next: "Следующая страница",
        page_add: "Добавить страницу",
        prompt_title: "Ввод",
        prompt_input: "Поле ввода",
        ok: "ОК",
        insert: "Вставить",
        filters: "Фильтры",
        sort_by: "Сортировка",
        sort_updated: "По времени изменения",
        sort_relevance: "По релевантности",
        sort_importance: "По важности",
        sort_title: "По алфавиту",
        sort_length: "По количеству символов",
        sort_manual: "Вручную",
        filter_folders: "Папки",
        align_menu: "Выравнивание",
        align_left: "По левому краю",
        align_center: "По центру",
        align_right: "По правому краю",
        reset_media: "Сбросить размер",
        delete: "Удалить",
        photo_color: "Цвет кисти",
        photo_width: "Толщина кисти",
        clear: "Очистить",
        folder_view_aria: "Режим отображения папок",
        color_text: "Цвет текста",
        color_accent: "Акцентный цвет",
        color_bg: "Цвет фона",
        feedback_aria: "Ваш отзыв",
        theme_light: "Светлая",
        theme_dark: "Темная",
        theme_system: "Системная",
        theme_high_contrast: "Высокий контраст",
        theme_oled: "OLED",
        theme_monochrome: "Монохром",
        theme_pastel: "Пастель",
        theme_warm: "Теплая",
        theme_cold: "Холодная",
        theme_minimal: "Минимал",
        theme_compact: "Компактная",
        theme_spacious: "Просторная",
        theme_accessibility: "Доступность",
        theme_glass: "Стекло",
        theme_matte: "Матовая",
        theme_neon: "Неон",
        theme_paper: "Бумага",
        theme_sunrise: "Рассвет",
        theme_ocean: "Океан",
        settings_menu_title: "Настройки",
        settings_general: "Общие",
        settings_appearance: "Внешний вид",
        settings_editor_tools: "Инструменты редактора",
        settings_back: "Назад",
        settings_category_general_desc: "Язык, папки и анимация",
        settings_category_appearance_desc: "Темы и цвета интерфейса",
        settings_category_editor_tools_desc: "Панель инструментов",
        smart_features: "УМНЫЕ ФУНКЦИИ",
        lock_center: "Защита заметок",
        lock_center_desc: "Тут будут фильтры скрытых заметок и быстрые действия",
        lock_center_empty: "Нет защищенных заметок",
        lock_center_masked_title: "Защищенная заметка",
        move_to_folder: "Переместить",
        folder_none: "Без папки",
        share_desc: "Ссылка будет сгенерирована и появится здесь",
        share_modal_title: "Поделиться",
        collab_title: "Совместное редактирование",
        collab_desc: "Одноразовая ссылка будет сгенерирована и появится здесь",
        copy: "Копировать",
        apply: "Применить",
        lock_title: "Блокировка",
        lock_password: "Пароль",
        lock_password_empty: "Пароль пустой",
        lock_invalid_password: "Неверный пароль",
        lock_hidden: "Заметка скрыта",
        lock_download_blocked: "Заметка заблокирована",
        note_deleted: "Удалено",
        folder_deleted: "Папка удалена",
        feedback_failed: "Не удалось отправить отзыв",
        reorder_search_disabled: "Сортировка недоступна при поиске",
        reorder_pinned_blocked: "Закрепленные заметки сортируются отдельно",
        reorder_folder_disabled: "Сортировка доступна только внутри папки или для заметок без папки",
        reorder_sort_disabled: "Переключитесь на ручную сортировку для перемещения",
        collab_enabled: "Совместный режим включен",
        share_note: "Поделиться заметкой",
        collab_note: "Совместное редактирование",
        lock_note: "Заблокировать заметку",
        unlock_note: "Открыть",
        unlock_forever: "Снять защиту",
        unlock_success: "Заметка разблокирована",
        media_photo: "фото",
        media_photos: "фото",
        media_audio: "аудио",
        media_audios: "аудио",
        nav_aria: "Навигация",
        sections_aria: "Разделы",
        notes_list_aria: "Список заметок",
        user_menu: "Пользователь",
        editor_actions: "Действия редактора",
        editor_toolbar: "Инструменты редактора",
        tags_aria: "Теги",
        media_menu: "Меню изображения",
        rating_aria: "Оценка",
        login_aria: "Авторизация",
        theme_dark_default: "Темная",
        theme_graphite: "Графит",
        theme_neon_cyan: "Неоновый циан",
        theme_emerald_calm: "Изумрудный покой",
        theme_violet_pulse: "Фиолетовый импульс",
        theme_crimson_glow: "Алый жар",
        theme_amber_wave: "Янтарная волна",
        theme_rose_blush: "Розовый румянец",
        theme_ocean_deep: "Глубокий океан",
        theme_oled_pure: "OLED черный",
        theme_manual: "Вручную",
        auth_popup_closed: "Вход отменен",
        auth_network_failed: "Нет соединения с интернетом",
        auth_cancelled: "Запрос отменен",
        logout_failed: "Ошибка при выходе",
        login_failed: "Ошибка входа",
        favorite_failed: "Не удалось обновить избранное",
        unlock_failed: "Не удалось открыть заметку",
        draw_photo_hint: "Откройте редактор фото",
        password_title: "Пароль",
        password_prompt: "Введите пароль"
    },
    en: {
        app_name: "SmartNotes",
        slogan: "Your thoughts. Organized.",
        login: "Sign in",
        login_google: "Sign in with Google",
        all_notes: "All Notes",
        favorites: "Important",
        archive: "Archive",
        hidden_notes: "Hidden",
        future_notes: "Future",
        folders: "FOLDERS",
        folders_overview: "Folders",
        about: "About",
        rate: "Rate Us",
        settings: "Settings",
        switch_acc: "Switch",
        logout: "Logout",
        empty: "Nothing here yet",
        general: "General",
        language: "Language",
        appearance: "Appearance",
        presets: "Presets",
        manual: "Manual Config",
        c_text: "Text",
        c_accent: "Accent",
        c_bg: "Background",
        reset: "Reset",
        close: "Close",
        save: "Save",
        team: "Team",
        contact_us: "Contact us:",
        send: "Send",
        cancel: "Cancel",
        yes: "Yes",
        search: "Search...",
        note_title: "Title",
        note_tags: "#tag (Enter)",
        feedback_placeholder: "Share your feedback...",
        note_actions: "Actions",
        audio_note: "Audio",
        download_note: "Download file",
        upload_note: "Upload to cloud",
        photo_editor: "Photo Editor",
        folders_settings: "Folders",
        folder_view_mode: "Folder display in menu",
        folder_view_compact: "Sidebar list",
        folder_view_full: "Full view",
        reduce_motion: "Reduce motion",
        visual_effects: "Visual effects",
        editor_settings: "Editor settings",
        view_notes: "All Notes",
        view_favorites: "Important",
        view_archive: "Archive",
        view_hidden: "Hidden",
        view_future: "Future",
        view_folder: "Folder",
        view_folders: "Folders",
        view_locked: "Note Protection",
        hidden_empty: "No hidden notes",
        future_empty: "No future notes",
        note_single: "note",
        note_plural: "notes",
        folders_empty: "No folders yet",
        pin_note: "Pin",
        unpin_note: "Unpin",
        favorite_note: "Favorite",
        archive_note: "Archive",
        restore_note: "Restore",
        untitled_note: "Untitled",
        empty_note: "No content",
        locked_note: "Locked",
        new_folder: "New folder",
        folder_placeholder: "Folder name",
        folder_empty: "Enter a folder name",
        folder_exists: "Folder already exists",
        folder_limit: "Folder limit reached",
        rename_folder: "Rename folder",
        archived: "Archived",
        restored: "Restored",
        saving: "Saving...",
        saved: "Saved",
        rate_required: "Please rate the app",
        feedback_thanks: "Thanks!",
        order_updated: "Order updated",
        undo: "Undo",
        import_file: "Import file",
        import_invalid: "Unsupported file",
        import_empty: "No notes found",
        import_success: "Imported",
        import_failed: "Import failed",
        download_success: "File saved",
        drive_connected: "Drive connected",
        drive_unavailable: "Drive unavailable",
        drive_saved: "Uploaded to Drive",
        drive_error: "Drive upload failed",
        share_invalid: "Invalid link",
        share_missing: "Note not found",
        share_title: "Link",
        mic_unsupported: "Microphone not supported",
        mic_denied: "Microphone access denied",
        recording: "Recording...",
        reminder_set: "Reminder set",
        confirm_delete: "Delete?",
        confirm_exit: "Sign out?",
        confirm_account: "Switch account?",
        confirm_delete_folder: "Delete folder?",
        confirm_default: "Confirm",
        auth_unavailable: "Authentication unavailable",
        move_toolbar: "Move toolbar",
        toolbar_show: "Show toolbar",
        toolbar_hide: "Hide toolbar",
        tool_bold: "Bold",
        tool_italic: "Italic",
        tool_underline: "Underline",
        tool_bullets: "Bulleted list",
        tool_numbered: "Numbered list",
        tool_image: "Image",
        tool_sketch: "Sketch",
        tool_align: "Alignment",
        tool_clear: "Clear formatting",
        hide_note: "Hide from view",
        unhide_note: "Unhide",
        note_hidden: "Note hidden",
        note_unhidden: "Note unhidden",
        future_note: "Schedule",
        future_clear: "Clear schedule",
        future_saved: "Scheduled",
        future_cleared: "Schedule cleared",
        future_required: "Pick a date",
        copy_text: "Copy text",
        copy_success: "Copied",
        copy_failed: "Copy failed",
        share_imported: "Note added",
        polls: "Polls",
        poll_title: "Poll",
        poll_topic_label: "Poll topic",
        poll_answer_label: "Answer",
        poll_required: "Fill in the poll",
        poll_failed: "Unable to send poll",
        poll_thanks: "Thanks for your answer",
        sketch_inline_title: "Sketch",
        sketch_inline_aria: "Sketch in editor",
        system_override: "System Override",
        close_menu: "Close menu",
        add_folder: "Create folder",
        open_menu: "Open menu",
        search_aria: "Search notes",
        create_note: "Create note",
        create_folder: "Create folder",
        editor: "Editor",
        back: "Back",
        redo: "Redo",
        delete_note: "Delete note",
        note_title_aria: "Note title",
        note_body_aria: "Note body",
        note_tags_aria: "Add tag",
        save_note: "Save",
        editor_pages: "Pages",
        page_prev: "Previous page",
        page_next: "Next page",
        page_add: "Add page",
        prompt_title: "Input",
        prompt_input: "Input field",
        ok: "OK",
        insert: "Insert",
        filters: "Filters",
        sort_by: "Sort by",
        sort_updated: "Recently updated",
        sort_relevance: "Relevance",
        sort_importance: "Importance",
        sort_title: "Title (A–Z)",
        sort_length: "Character count",
        sort_manual: "Manual",
        filter_folders: "Folders",
        align_menu: "Alignment",
        align_left: "Align left",
        align_center: "Align center",
        align_right: "Align right",
        reset_media: "Reset size",
        delete: "Delete",
        photo_color: "Brush color",
        photo_width: "Brush width",
        clear: "Clear",
        folder_view_aria: "Folder view mode",
        color_text: "Text color",
        color_accent: "Accent color",
        color_bg: "Background color",
        feedback_aria: "Your feedback",
        theme_light: "Light",
        theme_dark: "Dark",
        theme_system: "System",
        theme_high_contrast: "High Contrast",
        theme_oled: "OLED",
        theme_monochrome: "Monochrome",
        theme_pastel: "Pastel",
        theme_warm: "Warm",
        theme_cold: "Cold",
        theme_minimal: "Minimal",
        theme_compact: "Compact",
        theme_spacious: "Spacious",
        theme_accessibility: "Accessibility",
        theme_glass: "Glass",
        theme_matte: "Matte",
        theme_neon: "Neon",
        theme_paper: "Paper",
        theme_sunrise: "Sunrise",
        theme_ocean: "Ocean",
        settings_menu_title: "Settings",
        settings_general: "General",
        settings_appearance: "Appearance",
        settings_editor_tools: "Editor Tools",
        settings_back: "Back",
        settings_category_general_desc: "Language, folders, motion",
        settings_category_appearance_desc: "Themes and interface colors",
        settings_category_editor_tools_desc: "Toolbar tools",
        smart_features: "SMART FEATURES",
        lock_center: "Note Protection",
        lock_center_desc: "Hidden notes filters and quick actions will appear here",
        lock_center_empty: "No protected notes",
        lock_center_masked_title: "Protected note",
        move_to_folder: "Move",
        folder_none: "No folder",
        share_desc: "A link will be generated and appear here",
        share_modal_title: "Share",
        collab_title: "Collaboration",
        collab_desc: "A one-time link will be generated and appear here",
        copy: "Copy",
        apply: "Apply",
        lock_title: "Lock",
        lock_password: "Password",
        lock_password_empty: "Password is empty",
        lock_invalid_password: "Invalid password",
        lock_hidden: "Note hidden",
        lock_download_blocked: "Note is locked",
        note_deleted: "Deleted",
        folder_deleted: "Folder deleted",
        feedback_failed: "Unable to send feedback",
        reorder_search_disabled: "Reordering is disabled while searching",
        reorder_pinned_blocked: "Pinned notes reorder separately",
        reorder_folder_disabled: "Reordering is available only inside folders or for notes without folders",
        reorder_sort_disabled: "Switch to manual sorting to reorder",
        collab_enabled: "Collaboration enabled",
        share_note: "Share note",
        collab_note: "Collaborate",
        lock_note: "Lock note",
        unlock_note: "Unlock",
        unlock_forever: "Remove lock",
        unlock_success: "Note unlocked",
        media_photo: "photo",
        media_photos: "photos",
        media_audio: "audio",
        media_audios: "audio",
        nav_aria: "Navigation",
        sections_aria: "Sections",
        notes_list_aria: "Notes list",
        user_menu: "User menu",
        editor_actions: "Editor actions",
        editor_toolbar: "Editor toolbar",
        tags_aria: "Tags",
        media_menu: "Image menu",
        rating_aria: "Rating",
        login_aria: "Authentication",
        theme_dark_default: "Dark Default",
        theme_graphite: "Graphite",
        theme_neon_cyan: "Neon Cyan",
        theme_emerald_calm: "Emerald Calm",
        theme_violet_pulse: "Violet Pulse",
        theme_crimson_glow: "Crimson Glow",
        theme_amber_wave: "Amber Wave",
        theme_rose_blush: "Rose Blush",
        theme_ocean_deep: "Ocean Deep",
        theme_oled_pure: "OLED Pure",
        theme_manual: "Manual",
        auth_popup_closed: "Sign-in canceled",
        auth_network_failed: "No internet connection",
        auth_cancelled: "Request canceled",
        logout_failed: "Sign out failed",
        login_failed: "Sign-in failed",
        favorite_failed: "Unable to update favorite",
        unlock_failed: "Unable to unlock note",
        draw_photo_hint: "Open the photo editor",
        password_title: "Password",
        password_prompt: "Enter password"
    }
}

window.LANG = LANG
